modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="create_enchantment_industry"
version="${file.jarVersion}"
displayName="Create Enchantment Industry"
logoFile="pack.png"
authors="MarbleGateKeeper & LimonBlaze"
description='''
Automatic Enchanting, with Create.
'''
[[dependencies.create_enchantment_industry]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.create_enchantment_industry]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.create_enchantment_industry]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,)"
    ordering="NONE"
    side="BOTH"
