modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="create_enchantment_industry" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Create Enchantment Industry" #mandatory
logoFile="pack.png" #optional
authors="MarbleGateKeeper & LimonBlaze" #optional
description='''
Automatic Enchanting, with Create.
'''
[[dependencies.create_enchantment_industry]]
modId="forge" #mandatory
mandatory=true
versionRange="[47,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.create_enchantment_industry]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.create_enchantment_industry]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"
